### ISSUE TITLE
When utilizing private GitHub Actions Runners, read IAM access from instance

### ISSUE THREAD

**Issue by jcam** [action-factory/aws-secrets-manager-action#5]
When using a private GitHub Actions Runner, it would be very useful to allow parsing the IAM access credentials from the instance profile, utilizing the workflow attributes as overrides.

**Comment by abhilash1in** [comment]
From [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials):

> For applications, AWS CLI, and Tools for Windows PowerShell commands that run on the instance, you do not have to explicitly get the temporary security credentials—the AWS SDKs, AWS CLI, and Tools for Windows PowerShell automatically get the credentials from the EC2 instance metadata service and use them.

I think simply omitting `accessKeyId` and `secretAccessKey` in the below snippet should do the trick.

https://github.com/action-factory/aws-secrets-manager-action/blob/98c59d606cdcc7986382e9d3b6e7be50db9fba25/src/index.ts#L11-L15

I can work on this but I have no way to test it since I don't have a self-hosted EC2 based GitHub Actions Runner (yet). 

@jcam will you be able to alpha-test the fix once I'm done?

**Comment by jcam** [comment]
Hmmmmmmm, actually it appears that if I just leave the keys out, it may just work without any changes!

Having trouble testing though... my secret is of the form "/dev/secrets/my_secret" and the workflow does not like the format env.dev/secrets/my_secret :/

**Comment by jcam** [comment]
First I have to see it read a secret...

**Comment by jcam** [comment]
I've discovered that this works without modification!
